name: PR Build

on:
  pull_request:
    paths-ignore:
      - '**.md'

env:
  gradleFlags: --parallel --stacktrace --no-configuration-cache --no-daemon
  CHAT_ID: ${{ secrets.CHAT_ID }}
  TG_TOKEN: ${{ secrets.TG_TOKEN }}

jobs:
  build-and-telegram-report:
    runs-on: ubuntu-latest
    outputs:
      build_number: ${{steps.buildnumber.outputs.build_number}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Generate build number
        id: buildnumber
        uses: onyxmueller/build-tag-number@v1
        with:
          token: ${{secrets.github_token}}
        env:
          versionCode: ${{steps.buildnumber.outputs.build_number}}
      - name: Grant execute permission for gradlew
        shell: bash
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew :app:reportTelegramApkForDebug $gradleFlags
      - name: Upload apk
        uses: actions/upload-artifact@v4
        with:
          name: todolist-debug.apk
          path: app/build/outputs/apk/debug/todolist-debug.apk